# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pineau <pineau@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/11 17:00:47 by pineau            #+#    #+#              #
#    Updated: 2023/02/15 15:13:00 by pineau           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME    = fractol

# Compiler
CC        = gcc
#CFLAGS    = -Werror -Wextra -Wall -g3

# Minilibx
MLX_PATH    = ./mlx_linux/
MLX_NAME    = libmlx.a
MLX            = $(MLX_PATH)$(MLX_NAME)

# Includes
INC            =    -I ./include/\
                -I $(MLX_PATH)

# Sources
SRC_PATH    =    ./srcs/
SRC            =    \
                fractol.c\
				test.c\
                    
SRCS        = $(addprefix $(SRC_PATH), $(SRC))

# Objects
OBJ_PATH    = obj/
OBJ            = $(SRC:.c=.o)
OBJS        = $(addprefix $(OBJ_PATH), $(OBJ))

all: $(MLX) $(NAME)

$(OBJ_PATH)%.o: $(SRC_PATH)%.c
	@$(CC) $(CFLAGS) -c $< -o $@ $(INC)

$(OBJS): $(OBJ_PATH)

$(OBJ_PATH):
	@mkdir $(OBJ_PATH)
    
$(MLX):
	@echo "Making MiniLibX..."
	@make -sC $(MLX_PATH)

$(NAME): $(OBJS)
	@echo "Compiling fractol..."
	@$(CC) $(CFLAGS) -o $(NAME) $(OBJS) $(MLX) $(INC) -lXext -lX11 -lm
	@echo "Fractol ready."

norm:
	norminette $(INC)
	@printf "\n$(G)=== No norminette errors found in $(INC) ===$(RC)\n\n"
	norminette $(SRC_PATH)
	@printf "\n$(G)=== No norminette errors found in $(SRC_PATH) ===$(RC)\n\n"
    
clean:
	@echo "Removing .o object files..."
	@rm -rf $(OBJ_PATH)
	@make clean -C $(MLX_PATH)
#	@make clean -C $(LIBFT_PATH)

fclean: clean
	@echo "Removing fractol..."
	@rm -f $(NAME)
    
re: fclean all

.PHONY: all bonus norm re clean fclean